# This is a basic workflow to help you get started with boman.ai

name: Bomanai Scanner QA
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Boman-scan:
    # The type of runner that the job will run on
    environment: prod
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install packages
        run: sudo pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat
        # run: sudo pip install boman-cli
      - name: Run scan
        env:
          APP: ${{ secrets.APP_TOKEN }}
          USER: ${{ secrets.CUSTOMER_TOKEN }}
        # run: sudo boman-cli-uat -a run -u https://qa.boman.ai -at e3a1dd22-f01f-4bcb-aa65-a96c7ebceb48 -ct 5b2f4dbd-a873-4042-8441-ff38fef71ed5
        # run: sudo boman-cli-uat -a run -u https://qa.boman.ai -at "$APP" -ct "$USER"
        # run: sudo boman-cli-uat -a run  -u https://qa.boman.ai
