# This is a basic workflow to help you get started with boman.ai

name: Bomanai Scanner Local
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Boman-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Install packages
        run: sudo pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat
      - name: Run scan  
        run: sudo boman-cli-uat -a run -u https://98a2-2401-4900-8845-7fd6-e8b2-c96d-795c-b38a.ngrok-free.app -at 6b8383c3-a928-4709-845f-05efeb9c5b1c -ct 4941f85a-5453-4f94-9247-d5565b4bd116
